---
Parameters:
  Ec2StackName:
    Description: The name of the stack containing the resources
    Type: String

Resources:
  473019369EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc 
      Tags:
        - Key: Name
          Value: 473019369EIP

  473019369IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt 473019369EIP.AllocationId
      InstanceId: 
        Fn::ImportValue: !Sub "${Ec2StackName}-473019369EC2"

Outputs:
  473019369EIP:
    Description: The allocated Elastic IP
    Value: !Ref 473019369EIP
